server {
  listen 80 default_server;
  listen [::]:80 default_server ipv6only=on;
  
  location /.well-known {
    alias /var/www/node99.frentzel.xyz/.well-known;
  }
  
  location / {
    return 301 https://$host$request_uri;
  }
}
