#!/bin/bash

sudo apt update

# Base System
sudo apt -y install \
build-essential \
clojure \
default-jdk \
file \
flex \
gawk \
gcc-multilib \
gettext \
git \
gnupg \
golang \
libbz2-dev \
libffi-dev \
liblzma-dev \
libncurses5-dev \
libreadline-dev \
libsqlite3-dev \
libssl-dev \
locales-all \
micro \
nodejs \
npm \
python3 \
python3-setuptools \
python3-poetry \
rsync \
swig \
tk-dev \
tmux \
unzip \
wget \
zlib1g-dev
