#!/bin/bash

__mp4c() {
    OUTPUT_DIR="$1"
    INPUT_FILE="$2"
    filename=$(basename "${INPUT_FILE}")
    extension="${filename##*.}"
    echo "[Converting] ${filename}"
    ffmpeg -threads 4 -i "${INPUT_FILE}" \
      -map_metadata -1 \
      -map 0:0 -map 0:1 \
      -c:v copy \
      -c:a copy \
      -f mp4 "${OUTPUT_DIR}/${filename/%.${extension}/.mp4}" &
    wait $!
}
export -f __mp4c
find $1 -type f \( -iname \*.mp4 -o -iname \*.avi -o -iname \*.mkv \) \
  -exec bash -c "__mp4c \"$2\" \"{}\"" \;
