#!/bin/bash

__mp4c() {
    OUTPUT_DIR="$1"
    INPUT_FILE="$2"
    filename=$(basename "${INPUT_FILE}")
    extension="${filename##*.}"
    if ffprobe "${INPUT_FILE}" 2>&1 | grep -q "Video: h264" || \
      ffprobe "${INPUT_FILE}" 2>&1 | grep -q "Video: hevc"
    then
      vcodec=copy
    else
      vcodec=libx265
    fi
    if ffprobe "${INPUT_FILE}" 2>&1 | grep -q "Audio: aac"
    then
      acodec=copy
    else
      acodec=aac
    fi
    echo "[Converting] ${filename} (${vcodec}/${acodec})"
    ffmpeg -threads 4 -i "${INPUT_FILE}" \
      -strict experimental -map_metadata -1 \
      -map 0 -map -0:s \
      -c:v ${vcodec} -preset medium -crf 23 \
      -c:a ${acodec} -b:a 192k \
      -f mp4 "${OUTPUT_DIR}/${filename/%.${extension}/.mp4}" &
    wait $!
}
export -f __mp4c
find $1 -type f \( -iname \*.mp4 -o -iname \*.avi -o -iname \*.mkv \) \
  -exec bash -c "__mp4c \"$2\" \"{}\"" \;
