#!/bin/bash
out=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ 2>/dev/null)
if echo "$out" | grep -q MUTED; then
    printf '\xef\x80\xa6 muted'
else
    printf '\xef\x80\xa8 %d%%' "$(echo "$out" | awk '{printf "%d", $2*100}')"
fi
