#!/bin/sh

ip rule | sed -n 's/.*\(from[ \t]*[0-9\.]*\).*vpn/\1/p' | while read rule
do
    ip rule del ${rule}
done

ip route del 128.0.0.0/1 via ${route_vpn_gateway}
ip route del 0.0.0.0/1 via ${route_vpn_gateway}
ip rule add from ${ifconfig_local} lookup $ROUTE_TABLE
ip route flush table $ROUTE_TABLE
ip route add default dev ${dev} table $ROUTE_TABLE
systemctl restart qbittorrent

exit 0
