#! /bin/bash

apt-get install \
anacron \
bash-completion \
cryptsetup \
locales \
ntp \
mdadm \
hdparm \
wireless-tools \
wpasupplicant \
firmware-linux-free \
firmware-iwlwifi \
firmware-realtek \
firmware-linux \
intel-microcode \
thermald \
avahi-daemon \
openssh-server \
openssh-client \
sudo \
rsync
