#! /bin/bash

sudo apt-get install \
anacron \
ntp \
parted \
cryptsetup \
mdadm \
hdparm \
wireless-tools \
wpasupplicant \
firmware-linux-free \
firmware-iwlwifi \
firmware-realtek \
firmware-linux \
intel-microcode \
dropbear \
openssh-client \
openssh-sftp-server \
debootstrap \
git \
rsync \
ca-certificates \
bash-completion \
tmux \
tree \
pwgen \
gnupg
